[language-server.gopls.config]
[language-server.gopls.config.source]
organizeImports = true

[langauge-server.gopls.config.ui.diagnostic]
staticcheck = true

[language-server.gopls.config.hints]
compositeLiteralFields = true
compositeLiteralTypes = true
assignVariableTypes = true
parameterNames = true
rangeVariableTypes = true

[[language]]
name = "go"
indent = { tab-width = 8, unit = "\t" }
text-width = 80

[[language]]
name = "gomod"
indent = { tab-width = 8, unit = "\t" }

[[language]]
name = "gowork"
indent = { tab-width = 8, unit = "\t" }

[[language]]
name = "git-commit"
comment-token = ";"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "git-rebase"
comment-token = ";"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "python"
auto-format = true
